name: Build terminal
on:
    push:
        branches:
            - master
        paths-ignore:
            - 'README.md'
            - 'LICENSE'
            - '.gitignore'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Install make
          run: sudo apt make

        - name: Install deps
          run: make deps

        - name: Build terminal
          run: make build

        - uses: actions/upload-artifact@v4
          with:
            name: Terminal
            path: bin/terminal